### ISSUE TITLE
[DonateBot] confirmation/warning for "no reward" donations

### ISSUE THREAD

**Issue by fatchan** [top-gg/donatebot-issues#47]
#### Suggestion

There should be a warning/confirmation before allowing users to donate with no reward/no name selected. At least 50% of my donations do not select a user from the dropdown, then DM me frustrated or dispute payment when it is not automatically processed (because i dont get a user ID in webhook for donation-only transactions) and they do not get assigned a role. Users dont understand that the donatebot page has no way of associating payment with a user without selecting their name from the dropdown. 
Alternatively, just make there be no option in the selection box i.e. not "no reward" by default. That way, a user is required to click the dropdown and either select no reward, or their username before donating.

Thanks :+1:

**Comment by jczstudios** [comment]
This was added, you can also update a subscription after they have purchased now using the subscriptions button inside the transactions tab on the panel.
